### PR TITLE
refactor: use children prop more + small improvements

### LINKED ISSUE #21: Support using children as the content for single-root renderers
For component renderers that only render to a single root, it would be convenient not to have to use a renderer function in the React API at all, but instead [to use the children for the content](https://github.com/tomivirkki/react-vaadin-components/blob/cc2cc6421e04ea8db2031881a501a9cabc2d2fcd/src/create-component.ts#L203-L238). This would be applicable for components such as `Dialog` (content, header, footer) and `Notification`:

```jsx
<Dialog>
  <div>Dialog content</div>
</Dialog>
```

instead of

```jsx
<Dialog renderer={() => {
  return <div>Dialog content</div>
}}>
```

The latter syntax is preferable for renderers that render items to multiple roots (`ComboBox`, `GridColumn` renderer)

### PR DESCRIPTION
**Pull request by Lodin**
Resolves #21

### CODE REVIEW

**Comment by platosha** [comment]
Personally I find it a bit confusing to use children for `useModelRenderer` use cases, as the component would stamp an arbitrary number of child items from what looks like only one child in the code. WDYT? Should we only support `children` for the single stamping use cases?

**Comment by Lodin** [comment]
@platosha, actually, that's quite the common thing in React world. E.g., take a look on the [react-window](https://github.com/bvaughn/react-window) library; it uses the same approach.

**Comment by platosha** [comment]
Field components (combo-box, select) have many sometime useful slots (`label`, `prefix`, `suffix`, `helper`, `error-message`...). If children are used for renderer, does it mean that we can no longer use any slot?

**Comment by Lodin** [comment]
Yep, that's a problem. Could you list all the components with slots? I'll get their children back.

**Comment by platosha** [comment]
@Lodin those have slots that I found to be useful:
```
Checkbox.tsx
ComboBox.tsx
ComboBoxLight.tsx
ConfirmDialog.tsx
ContextMenu.tsx
Select.tsx
```

**Comment by Lodin** [comment]
@platosha, ok, I've reverted the changes I made for these components

**Comment by platosha** [comment]
Another thing is, `Dialog` and `Notification` drop the renderer property entirely, whereas `GridColumn` family uses `renderer` in addition to children, and components that support slots only have `renderer`. Would it be a bit more consistent if we don’t drop `renderer` in `Dialog` and `Notification` too?

To me it seems beneficial to keep API consistent across the set and between web and React components. Having less of little differences simplifies learning and documenting features.

**Review by platosha — APPROVED** [review]

**Pull request merged**
